server:
  servlet:
    context-path: /pagingsorting
  port : 8030
#eureka configurations
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    hostname: false
#cors configurations
cors:
  allowedOrigins: "https://localhost:8030"

#actuator configurations
management:
  endpoints:
    health:
      enabled: true
    info:
      enabled: true
    web:
      base-path: /actuator
      exposure:
        include: health, info

spring:
  cloud:
    config:
      import-check:
        enabled: false
    import:
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    #with this absolute direction the data is save permantly, the information on database
    #with the value AUTO_SERVER = true, that made that you can open the h2 console without errors
    url: jdbc:h2:D:\tools\h2_Database;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#https://enmilocalfunciona.io/por-que-utilizar-arquetipos-maven/

#paging with springboot
#https://daviddelatorre.me/paginacion-con-spring-data/